(()=>{
'use strict';
const $=id=>document.getElementById(id);
const screens=['welcomeNew','loginNew','registerNew','commandNew','requestNew','teamNew'];
const show=id=>{screens.forEach(name=>$(name)?.classList.toggle('active',name===id));window.scrollTo(0,0)};
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const users=()=>read('heuroUsers');
const requests=()=>read('heuroRequests');
const saveUsers=data=>localStorage.setItem('heuroUsers',JSON.stringify(data));
const saveRequests=data=>localStorage.setItem('heuroRequests',JSON.stringify(data));
function seed(){const data=users();if(data.length)return;data.push({id:'admin-inicial',fullName:'Tiago Pereira de Albuquerque',username:'Tiago',password:'1234',profile:'administrador',status:'ativo'});saveUsers(data)}
function session(){try{return JSON.parse(sessionStorage.getItem('heuroSession')||'null')}catch{return null}}
function protocol(){const d=new Date();const date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return`HEURO-${date}-${String(Date.now()).slice(-5)}`}
function formatDate(value){if(!value)return'Não informada';const[y,m,d]=String(value).split('-');return y&&m&&d?`${d}/${m}/${y}`:value}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function locationText(item){return item.boxNumber?`Box ${item.boxNumber}`:`${item.ward||'Enfermaria não informada'} · Leito ${item.bed||'não informado'}`}
function bindUppercaseName(id){const field=$(id);if(!field)return;field.setAttribute('autocapitalize','characters');field.setAttribute('autocomplete','name');field.style.textTransform='uppercase';field.addEventListener('input',()=>{const start=field.selectionStart,end=field.selectionEnd,upper=field.value.toLocaleUpperCase('pt-BR');if(field.value!==upper){field.value=upper;try{field.setSelectionRange(start,end)}catch{}}})}
function renderTeam(){const box=$('teamListNew');if(!box)return;const data=requests().sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));if(!data.length){box.innerHTML='<div class="card empty-state"><strong>Nenhum transporte cadastrado.</strong><p>As solicitações salvas aparecerão aqui para acompanhamento da equipe.</p></div>';return}box.innerHTML=data.map(item=>`<article class="transport-card"><div class="transport-top"><span class="status-pill status-${String(item.status||'solicitado').toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${escapeHtml(item.status||'Solicitado')}</span><small>${escapeHtml(item.protocol||'Sem protocolo')}</small></div><h3>${escapeHtml(item.patient||'Paciente não informado')}</h3><p><b>Origem:</b> ${escapeHtml(item.originSector||'Não informada')} — ${escapeHtml(locationText(item))}</p><p><b>Destino:</b> ${escapeHtml(item.destination||'Não informado')}</p><div class="transport-meta"><span>${formatDate(item.transportDate)} às ${escapeHtml(item.transportTime||'--:--')}</span><span>${escapeHtml(item.ambulanceType||'Ambulância não informada')}</span><span>${escapeHtml(item.priority||'Prioridade não informada')}</span></div></article>`).join('')}
seed();
bindUppercaseName('patientNew');
$('welcomeEnterNew')?.addEventListener('click',()=>show('loginNew'));
$('welcomeChangeNew')?.addEventListener('click',()=>{sessionStorage.removeItem('heuroSession');if($('loginUser'))$('loginUser').value='';if($('loginPass'))$('loginPass').value='';show('loginNew')});
$('openRegisterNew')?.addEventListener('click',()=>show('registerNew'));
$('loginFormNew')?.addEventListener('submit',e=>{e.preventDefault();const username=$('loginUser').value.trim().toLowerCase(),password=$('loginPass').value,user=users().find(item=>String(item.username||'').trim().toLowerCase()===username),msg=$('loginMessageNew');if(!user||user.password!==password){msg.textContent='Nome de usuário ou senha incorretos.';return}if(user.status!=='ativo'){msg.textContent='Seu acesso ainda não está ativo.';return}sessionStorage.setItem('heuroSession',JSON.stringify({id:user.id,name:user.fullName||user.username,username:user.username,profile:user.profile}));msg.textContent='';show('commandNew')});
$('cmdLogout')?.addEventListener('click',()=>{sessionStorage.removeItem('heuroSession');show('welcomeNew')});
$('cmdNew')?.addEventListener('click',()=>show('requestNew'));
$('requestBackNew')?.addEventListener('click',()=>show('commandNew'));
$('cmdTeam')?.addEventListener('click',()=>{renderTeam();show('teamNew')});
$('teamBackNew')?.addEventListener('click',()=>show('commandNew'));
$('originSectorNew')?.addEventListener('change',()=>{const usesBox=['Sala Vermelha','UTI'].includes($('originSectorNew').value);$('boxGroupNew').style.display=usesBox?'block':'none';$('wardGroupNew').style.display=usesBox?'none':'grid';$('boxNew').required=usesBox;$('wardNew').required=!usesBox;$('bedNew').required=!usesBox});
$('requestFormNew')?.addEventListener('submit',e=>{e.preventDefault();const s=session(),usesBox=['Sala Vermelha','UTI'].includes($('originSectorNew').value),file=$('attachmentNew').files?.[0],item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),protocol:protocol(),status:'Solicitado',createdAt:new Date().toISOString(),requester:s?.name||'Usuário',requesterId:s?.id||'',patient:$('patientNew').value.trim().toLocaleUpperCase('pt-BR'),birthDate:$('birthDateNew').value,originSector:$('originSectorNew').value,boxNumber:usesBox?$('boxNew').value.trim():'',ward:usesBox?'':$('wardNew').value.trim(),bed:usesBox?'':$('bedNew').value.trim(),destination:$('destinationNew').value.trim(),transportDate:$('transportDateNew').value,transportTime:$('transportTimeNew').value,ambulanceType:$('ambulanceTypeNew').value,priority:$('priorityNew').value,oxygen:$('oxygenNew').value,contact:$('contactNew').value.trim(),notes:$('notesNew').value.trim(),attachmentName:file?file.name:'Nenhum documento informado'};const data=requests();data.unshift(item);saveRequests(data);$('requestMessageNew').textContent=`Solicitação ${item.protocol} salva com sucesso.`;$('requestFormNew').reset();$('boxGroupNew').style.display='none';$('wardGroupNew').style.display='grid';setTimeout(()=>show('commandNew'),900)});
const pending=id=>$(id)?.addEventListener('click',()=>alert('Este botão será conectado na próxima etapa.'));
['cmdBell','cmdPending','cmdAgenda','cmdHistory','cmdTransport','cmdNotifications','cmdProfile','cmdMore'].forEach(pending);
$('cmdHome')?.addEventListener('click',()=>show('commandNew'));
show(session()?'commandNew':'welcomeNew');
})();

(()=>{
'use strict';
function isoToBr(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return'';const[y,m,d]=value.split('-');return`${d}/${m}/${y}`}
function brToIso(value){if(!/^\d{2}\/\d{2}\/\d{4}$/.test(value||''))return'';const[d,m,y]=value.split('/').map(Number),date=new Date(y,m-1,d);if(date.getFullYear()!==y||date.getMonth()!==m-1||date.getDate()!==d)return'';return`${String(y).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function mask(value){const digits=String(value||'').replace(/\D/g,'').slice(0,8);if(digits.length<=2)return digits;if(digits.length<=4)return`${digits.slice(0,2)}/${digits.slice(2)}`;return`${digits.slice(0,2)}/${digits.slice(2,4)}/${digits.slice(4)}`}
function init(){const native=document.getElementById('birthDateNew');if(!native||native.dataset.enhanced==='1')return;native.dataset.enhanced='1';native.id='birthDateNative';native.name='birthDateNative';native.style.cssText='position:absolute;opacity:0;pointer-events:none;width:1px;height:1px';const wrap=document.createElement('div');wrap.className='birth-date-control';const display=document.createElement('input');display.id='birthDateNew';display.type='text';display.inputMode='numeric';display.placeholder='DD/MM/AAAA';display.maxLength=10;display.autocomplete='bday';display.setAttribute('aria-label','Data de nascimento');const button=document.createElement('button');button.type='button';button.className='birth-date-calendar';button.setAttribute('aria-label','Abrir calendário');button.textContent='📅';native.parentNode.insertBefore(wrap,native);wrap.append(display,button,native);const help=document.createElement('small');help.className='birth-date-help';help.textContent='Digite a data ou selecione no calendário';wrap.parentNode.insertBefore(help,wrap.nextSibling);if(!document.getElementById('birthDateStyles')){const style=document.createElement('style');style.id='birthDateStyles';style.textContent='.birth-date-control{position:relative;display:flex;align-items:center;width:100%;min-width:0}.birth-date-control #birthDateNew{width:100%;height:48px;min-height:48px;padding:13px 54px 13px 13px;box-sizing:border-box}.birth-date-calendar{position:absolute;right:8px;top:50%;transform:translateY(-50%);width:40px;height:40px;border:0;background:transparent;font-size:24px;display:flex;align-items:center;justify-content:center;padding:0}.birth-date-help{display:block;margin-top:6px;color:#68758a;font-weight:400}.birth-date-control input:focus{outline:2px solid #8ec5ff;outline-offset:1px}';document.head.appendChild(style)}display.addEventListener('input',()=>{display.value=mask(display.value);native.value=brToIso(display.value)});display.addEventListener('blur',()=>display.setCustomValidity(display.value&&!brToIso(display.value)?'Informe uma data válida no formato DD/MM/AAAA.':''));button.addEventListener('click',()=>{try{native.showPicker()}catch{native.click()}});native.addEventListener('change',()=>{display.value=isoToBr(native.value);display.setCustomValidity('')});document.getElementById('requestFormNew')?.addEventListener('reset',()=>setTimeout(()=>{display.value='';native.value=''},0))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();