(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const DB_NAME='heuroTransportFiles';
  const STORE_NAME='attachments';
  const digits=value=>String(value||'').replace(/\D/g,'');
  const withBrazil=value=>{const n=digits(value);return n.startsWith('55')?n:`55${n}`};
  const readRequests=()=>{try{return JSON.parse(localStorage.getItem('heuroRequests')||'[]')}catch{return[]}};
  const saveRequests=data=>localStorage.setItem('heuroRequests',JSON.stringify(data));
  const session=()=>{try{return JSON.parse(sessionStorage.getItem('heuroSession')||'null')}catch{return null}};
  const protocol=()=>{const d=new Date();const date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `HEURO-${date}-${String(Date.now()).slice(-5)}`};
  const formatDate=value=>{if(!value)return'Não informado';const[y,m,d]=String(value).split('-');return y&&m&&d?`${d}/${m}/${y}`:value};
  const isUti=item=>String(item.ambulanceType||'').trim().toLowerCase()==='uti';
  const configuredNumber=item=>isUti(item)?localStorage.getItem('heuroWhatsappUti')||'':localStorage.getItem('heuroWhatsappBasic')||localStorage.getItem('heuroWhatsapp')||'';
  let lastSaved=null;

  function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');window.scrollTo(0,0)}
  function location(item){return item.boxNumber?`Box: ${item.boxNumber}`:`Enfermaria: ${item.ward||'Não informada'}\nLeito: ${item.bed||'Não informado'}`}
  function message(item){return `*SOLICITAÇÃO DE TRANSPORTE HEURO*\n\nProtocolo: ${item.protocol}\nPaciente: ${item.patient}\nSetor de origem: ${item.originSector||'Não informado'}\n${location(item)}\nDestino: ${item.destination}\nData: ${formatDate(item.transportDate)} às ${item.transportTime}\nAmbulância: ${item.ambulanceType}\nPrioridade: ${item.priority}\nOxigênio: ${item.oxygen}\nDocumento: ${item.attachmentName}\nObservações: ${item.notes||'Sem observações'}\n\nSolicitação registrada no aplicativo Transporte HEURO.`}

  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE_NAME))req.result.createObjectStore(STORE_NAME)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function saveAttachment(id,file){if(!id||!file)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).put({blob:file,name:file.name,type:file.type},id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
  async function getAttachment(id){const db=await openDb();const out=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readonly');const req=tx.objectStore(STORE_NAME).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)});db.close();return out}
  function loadJsPdf(){if(window.jspdf?.jsPDF)return Promise.resolve();return new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-heuro-jspdf]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('Falha ao carregar o gerador de PDF')),{once:true});return}const s=document.createElement('script');s.dataset.heuroJspdf='1';s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.onload=()=>window.jspdf?.jsPDF?resolve():reject(new Error('Gerador de PDF indisponível'));s.onerror=()=>reject(new Error('Falha ao carregar o gerador de PDF'));document.head.appendChild(s)})}
  function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
  function imageSize(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve({width:img.naturalWidth,height:img.naturalHeight});img.onerror=reject;img.src=src})}
  async function imageToJpeg(blob){const source=await blobToDataUrl(blob);const img=await new Promise((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=()=>reject(new Error('Não foi possível ler a foto anexada'));el.src=source});const maxSide=1800;const scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Não foi possível preparar a foto');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return{data:canvas.toDataURL('image/jpeg',0.82),width:canvas.width,height:canvas.height}}
  function addField(doc,label,value,x,y,width=82){doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(95,115,135);doc.text(label,x,y);doc.setFont('helvetica','normal');doc.setFontSize(12);doc.setTextColor(18,48,78);const lines=doc.splitTextToSize(String(value||'Não informado'),width);doc.text(lines,x,y+6);return y+6+lines.length*5}
  async function buildPdf(item){await loadJsPdf();const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4',compress:true});doc.setFont('helvetica','bold');doc.setFontSize(17);doc.setTextColor(18,48,78);doc.text('TRANSPORTE HEURO',105,16,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(90,105,120);doc.text('Solicitação de transporte',105,23,{align:'center'});doc.setDrawColor(215,225,235);doc.line(15,28,195,28);let yl=38,yr=38;yl=addField(doc,'Status',item.status,16,yl);yr=addField(doc,'Paciente',item.patient,108,yr);yl=addField(doc,'Nascimento',formatDate(item.birthDate),16,yl+5);yr=addField(doc,'Solicitante',item.requester,108,yr+5);yl=addField(doc,'Setor de origem',item.originSector,16,yl+5);yr=addField(doc,'Destino',item.destination,108,yr+5);yl=addField(doc,item.boxNumber?'Box':'Enfermaria / Leito',item.boxNumber||`${item.ward||'Não informada'} / ${item.bed||'Não informado'}`,16,yl+5);yr=addField(doc,'Data e hora',`${formatDate(item.transportDate)} às ${item.transportTime}`,108,yr+5);yl=addField(doc,'Prioridade',item.priority,16,yl+5);yr=addField(doc,'Ambulância',item.ambulanceType,108,yr+5);yl=addField(doc,'Oxigênio',item.oxygen,16,yl+5);yr=addField(doc,'Contato',item.contact||'Não informado',108,yr+5);let y=Math.max(yl,yr)+8;y=addField(doc,'Documento da regulação',item.attachmentName,16,y,178)+5;addField(doc,'Observações',item.notes||'Sem observações',16,y,178);const att=await getAttachment(item.id);if(att?.blob&&att.type?.startsWith('image/')){const prepared=await imageToJpeg(att.blob);doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('DOCUMENTO DA REGULAÇÃO',105,16,{align:'center'});const ratio=Math.min(180/prepared.width,258/prepared.height);const w=prepared.width*ratio,h=prepared.height*ratio;doc.addImage(prepared.data,'JPEG',(210-w)/2,29,w,h,undefined,'FAST')}return doc.output('blob')}

  function ensureActions(){let box=$('requestSavedActions');if(box)return box;box=document.createElement('div');box.id='requestSavedActions';box.style.cssText='display:none;margin-top:18px;padding:16px;border-radius:18px;background:#f3f8ff;border:1px solid #cfe0f4';box.innerHTML='<div style="display:grid;gap:12px"><button id="sendWhatsappNew" type="button" style="min-height:56px;border:0;border-radius:14px;background:#159447;color:#fff;font-weight:800;font-size:17px">Encaminhar ao WhatsApp</button><button id="downloadPdfNew" type="button" style="min-height:56px;border:0;border-radius:14px;background:#0b5fa5;color:#fff;font-weight:800;font-size:17px">Baixar PDF</button><button id="backCommandAfterSave" type="button" style="min-height:52px;border:0;border-radius:14px;background:#e8eef7;color:#13213a;font-weight:800;font-size:16px">Voltar para a tela de comando</button></div>';$('requestMessageNew')?.insertAdjacentElement('afterend',box);return box}
  async function downloadPdf(item){const blob=await buildPdf(item);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Transporte HEURO - ${item.protocol}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
  async function shareWhatsapp(item){const number=configuredNumber(item);if(!number){alert(`O número do ${isUti(item)?'transporte UTI':'transporte básico'} ainda não foi cadastrado em Mais > Configurar WhatsApp da empresa.`);return}const button=$('sendWhatsappNew');const original=button.textContent;button.disabled=true;button.textContent='Preparando PDF...';try{const blob=await buildPdf(item);const file=new File([blob],`Transporte HEURO - ${item.protocol}.pdf`,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:`Transporte HEURO - ${item.protocol}`,text:message(item),files:[file]})}else{await downloadPdf(item);window.open(`https://wa.me/${withBrazil(number)}?text=${encodeURIComponent(message(item))}`,'_blank')}}catch(error){if(error?.name!=='AbortError'){console.error(error);alert(`Não foi possível gerar o PDF. ${error?.message||'Tente novamente.'}`)}}finally{button.disabled=false;button.textContent=original}}

  document.addEventListener('submit',async event=>{
    if(event.target?.id!=='requestFormNew')return;
    event.preventDefault();event.stopImmediatePropagation();
    const s=session();const usesBox=['Sala Vermelha','UTI'].includes($('originSectorNew').value);const file=$('attachmentNew').files?.[0];
    const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),protocol:protocol(),status:'Solicitado',createdAt:new Date().toISOString(),requester:s?.name||'Usuário',requesterId:s?.id||'',patient:$('patientNew').value.trim(),birthDate:$('birthDateNew').value,originSector:$('originSectorNew').value,boxNumber:usesBox?$('boxNew').value.trim():'',ward:usesBox?'':$('wardNew').value.trim(),bed:usesBox?'':$('bedNew').value.trim(),destination:$('destinationNew').value.trim(),transportDate:$('transportDateNew').value,transportTime:$('transportTimeNew').value,ambulanceType:$('ambulanceTypeNew').value,priority:$('priorityNew').value,oxygen:$('oxygenNew').value,contact:$('contactNew').value.trim(),notes:$('notesNew').value.trim(),attachmentName:file?file.name:'Nenhum documento informado'};
    const data=readRequests();data.unshift(item);saveRequests(data);if(file){try{await saveAttachment(item.id,file)}catch(error){console.error('Falha ao armazenar anexo',error)}}lastSaved=item;$('requestMessageNew').textContent=`Solicitação ${item.protocol} salva com sucesso.`;ensureActions().style.display='block';$('requestFormNew').querySelector('button[type="submit"]').style.display='none';
  },true);

  document.addEventListener('click',event=>{if(event.target.closest('#sendWhatsappNew')&&lastSaved)shareWhatsapp(lastSaved);if(event.target.closest('#downloadPdfNew')&&lastSaved)downloadPdf(lastSaved).catch(error=>alert(`Não foi possível gerar o PDF. ${error?.message||''}`));if(event.target.closest('#backCommandAfterSave')){ensureActions().style.display='none';$('requestFormNew').reset();$('requestFormNew').querySelector('button[type="submit"]').style.display='block';$('requestMessageNew').textContent='';show('commandNew')}},true);
})();